name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - run: npm ci
      - uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: .

  prettier:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: .
      - run: npm run prettier

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: .
      - run: npm run lint