name: CI

on:
  # runs on pushes to the main branch
  push:
    branches:
      - 'master'
  # also runs inside pull requests that target the main branch
  pull_request:
    branches:
      - 'master'

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - run: npm ci
      - run: npm run prettier
      - run: npm run lint