name: CI

on:
  push:
  pull_request:
    branches:
      - master

install-steps: &install-steps
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
    with:
      node-version: "14"
      cache: "npm"
  - run: npm ci

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - <<: *install-steps

  prettier:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - <<: *install-steps
      - run: npm run prettier

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - <<: *install-steps
    - run: npm run lint